version = 1

[install]
addlicense.pkg-path = "addlicense"
addlicense.version = "1.1.1"
addlicense.pkg-group = "addlicense"

crane.pkg-path = "crane"
crane.version = "0.20.6"
crane.pkg-group = "crane"

ctlptl.pkg-path = "ctlptl"
ctlptl.version = "0.8.43"
ctlptl.pkg-group = "ctlptl"

curl.pkg-path = "curl"

git-cliff.pkg-path = "git-cliff"
git-cliff.version = "2.12.0"
git-cliff.pkg-group = "git-cliff"

go.pkg-path = "go"
go.version = "1.25"
go.pkg-group = "go"

go-licenses.pkg-path = "go-licenses"
go-licenses.version = "1.6.0"
go-licenses.pkg-group = "go-licenses"

golangci-lint.pkg-path = "golangci-lint"
golangci-lint.version = "2.6.2"
golangci-lint.pkg-group = "golangci-lint"

goreleaser.pkg-path = "goreleaser"
goreleaser.version = "2"
goreleaser.pkg-group = "goreleaser"

grype.pkg-path = "grype"
grype.version = "0"
grype.pkg-group = "grype"

# Build Helm 4 from source (not yet in nixpkgs)
# https://github.com/NixOS/nixpkgs/pull/461007
helm.flake = "gitlab:cmcdermott/flox?host=gitlab-master.nvidia.com&dir=flakes/helm/versions/v4.1.0"

jq.pkg-path = "jq"

kind.pkg-path = "kind"
kind.version = "0.31.0"
kind.pkg-group = "kind"

ko.pkg-path = "ko"
ko.version = "0.18.0"
ko.pkg-group = "ko"

kubectl.pkg-path = "kubectl"
kubectl.version = "1.32"
kubectl.pkg-group = "kubectl"

tilt.pkg-path = "tilt"
tilt.version = "0.35.0"
tilt.pkg-group = "tilt"

yamllint.pkg-path = "yamllint"
yamllint.version = "1.35"
yamllint.pkg-group = "yamllint"

yq.pkg-path = "yq-go"

[vars]
EIDOS_DEV = "true"

[profile]
common = '''
export GOPATH="${HOME}/go"
export PATH="${GOPATH}/bin:${PATH}"
'''
